### PR TITLE
HAPI-323 HNO table

### PR DESCRIPTION
**Pull request by mcarans**

### CODE REVIEW

**Comment by mcarans** [comment]
@davidmegginson I've updated this with the changes in document 14. 

I await answers to some questions here: https://humanitarian.atlassian.net/browse/HAPI-326, but in the meantime, I have included gender_description, sector_name, population_group_description and population_status_description in the humanitarian needs view and made population_status (ie. inneed, affected) mandatory in the humanitarian needs table. I can easily make changes to these.

**Review by davidmegginson — CHANGES_REQUESTED** [review]
Only minor variations (most are probably ok, but note the last one):

- gender\_code is char(1) in the schema design but str in SQLAlchemy
- reference\_period\_start/end is a timestamp in the schema design but the datetime class in SQLAlchemy 
- population\_status\_code is not required in the design but nullable=False in SQLAlchemy (we discussed this in Slack; still up in the air, and should probably confirm with the DPT)
- I’ve just added sector\_name to the view design (per your suggestion) so that it’s now consistent with your design
- (Please change) no need to add gender\_description (“m”, “f”, or “x” are fairly self-describing); ditto for population\_group\_description and population\_status\_description

**Comment by mcarans** [comment]
@davidmegginson I've changed population_status _code to nullable=True and removed gender_description, population_group_description and population_status_description.

I have changed gender_code to String(1), but left reference_period* as DateTime due to what it says in the [SQLAlchemy docs](https://docs.sqlalchemy.org/en/20/core/type_basics.html#the-camelcase-datatypes):

The rudimental types have “CamelCase” names such as [String](https://docs.sqlalchemy.org/en/20/core/type_basics.html#sqlalchemy.types.String), [Numeric](https://docs.sqlalchemy.org/en/20/core/type_basics.html#sqlalchemy.types.Numeric), [Integer](https://docs.sqlalchemy.org/en/20/core/type_basics.html#sqlalchemy.types.Integer), and [DateTime](https://docs.sqlalchemy.org/en/20/core/type_basics.html#sqlalchemy.types.DateTime). All of the immediate subclasses of [TypeEngine](https://docs.sqlalchemy.org/en/20/core/type_api.html#sqlalchemy.types.TypeEngine) are “CamelCase” types. The “CamelCase” types are to the greatest degree possible database agnostic"

**Comment by davidmegginson** [comment]
Thank you. Please go ahead and merge.

**Review by davidmegginson — APPROVED** [review]

**Pull request merged**
